from typing import overload


class Double:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    @staticmethod
    def abort_recording() -> None: ...

    def abs_me(self) -> Double: ...

    def acos_me(self) -> Double: ...

    def asin_me(self) -> Double: ...
